language: python
python:
    - 3.6

sudo: false
dist: trusty

install:
  - pip install pipenv
  - pipenv install --deploy --dev

addons:
  hosts:
    - testdb

env:
  - ENV=test

script:
  - make ci-test
