language: python
python:
    - 3.6

install:
  - pip install pipenv
  - pipenv install --deploy --dev

addons:
  apt:
    packages:
      - mysql-client-5.6
      - mysql-client-core-5.6
      - mysql-server-5.6
  hosts:
    - testdb

script:
  - make ci-test
